// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByUnPJzvpAi27wqVUgA9hsPtG0Jj5LvlU',
    appId: '1:97836459294:web:40f465509c6e4ab715150f',
    messagingSenderId: '97836459294',
    projectId: 'flutter-wanandroid',
    authDomain: 'flutter-wanandroid.firebaseapp.com',
    storageBucket: 'flutter-wanandroid.appspot.com',
    measurementId: 'G-SQ89XRNBPE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCK2jCj9oKpR385jB2N-s2xQu6Dja39oEQ',
    appId: '1:97836459294:android:7178a65930f0e63e15150f',
    messagingSenderId: '97836459294',
    projectId: 'flutter-wanandroid',
    storageBucket: 'flutter-wanandroid.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4diCcfBswfy8KbKuX-FR8ziTnN28biAc',
    appId: '1:97836459294:ios:46c538933a51e4e115150f',
    messagingSenderId: '97836459294',
    projectId: 'flutter-wanandroid',
    storageBucket: 'flutter-wanandroid.appspot.com',
    iosBundleId: 'com.lion.flutterWanandroid',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4diCcfBswfy8KbKuX-FR8ziTnN28biAc',
    appId: '1:97836459294:ios:d3b27d0f8e53180515150f',
    messagingSenderId: '97836459294',
    projectId: 'flutter-wanandroid',
    storageBucket: 'flutter-wanandroid.appspot.com',
    iosBundleId: 'com.example.flutterWanandroid2.RunnerTests',
  );
}
