// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByUnPJzvpAi27wqVUgA9hsPtG0Jj5LvlU',
    appId: '1:97836459294:web:40f465509c6e4ab715150f',
    messagingSenderId: '97836459294',
    projectId: 'flutter-wanandroid',
    authDomain: 'flutter-wanandroid.firebaseapp.com',
    storageBucket: 'flutter-wanandroid.firebasestorage.app',
    measurementId: 'G-SQ89XRNBPE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCK2jCj9oKpR385jB2N-s2xQu6Dja39oEQ',
    appId: '1:97836459294:android:7178a65930f0e63e15150f',
    messagingSenderId: '97836459294',
    projectId: 'flutter-wanandroid',
    storageBucket: 'flutter-wanandroid.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4diCcfBswfy8KbKuX-FR8ziTnN28biAc',
    appId: '1:97836459294:ios:46c538933a51e4e115150f',
    messagingSenderId: '97836459294',
    projectId: 'flutter-wanandroid',
    storageBucket: 'flutter-wanandroid.firebasestorage.app',
    iosBundleId: 'com.lion.flutterWanandroid',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4diCcfBswfy8KbKuX-FR8ziTnN28biAc',
    appId: '1:97836459294:ios:a0c9b348427c25e915150f',
    messagingSenderId: '97836459294',
    projectId: 'flutter-wanandroid',
    storageBucket: 'flutter-wanandroid.firebasestorage.app',
    iosBundleId: 'com.example.flutterWanandroid2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBeyVsOu4KRsiu0VG1uo_TiBZli71vFslE',
    appId: '1:97836459294:web:c191909c3b4ca26015150f',
    messagingSenderId: '97836459294',
    projectId: 'flutter-wanandroid',
    authDomain: 'flutter-wanandroid.firebaseapp.com',
    storageBucket: 'flutter-wanandroid.firebasestorage.app',
    measurementId: 'G-397BP7PMVZ',
  );
}
